// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_5kpnO4dXih11IqabDgMMJu5egSAbSc',
    appId: '1:323975104495:web:ee89f15afdfcb98752581a',
    messagingSenderId: '323975104495',
    projectId: 'usa-parking-app',
    authDomain: 'usa-parking-app.firebaseapp.com',
    storageBucket: 'usa-parking-app.appspot.com',
    measurementId: 'G-X24S593CS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADQZABHo0NxG2oicFIXCDuGE1e9Lzmkck',
    appId: '1:323975104495:android:3b5a69c2f3661ec952581a',
    messagingSenderId: '323975104495',
    projectId: 'usa-parking-app',
    storageBucket: 'usa-parking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEA7wAc-l6xhFMk6Rx1IXFhTDLyCz5GFA',
    appId: '1:323975104495:ios:8d3ce5f2e56428fe52581a',
    messagingSenderId: '323975104495',
    projectId: 'usa-parking-app',
    storageBucket: 'usa-parking-app.appspot.com',
    iosClientId: '323975104495-18o64bkohej735ff83lkcjf0ps0j4pmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.saYoloNg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEA7wAc-l6xhFMk6Rx1IXFhTDLyCz5GFA',
    appId: '1:323975104495:ios:1cfd9e66ff86dba952581a',
    messagingSenderId: '323975104495',
    projectId: 'usa-parking-app',
    storageBucket: 'usa-parking-app.appspot.com',
    iosClientId: '323975104495-m8vpi555sdlbfko78i00vjog6uhickd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.saYoloNg.RunnerTests',
  );
}
